[operator]
name="Željeznički prevoz Crne Gore"
url="https://zpcg.me"
phone="+382 20 441 197"
email="info@zpcg.me"
color="D82234"
text_color="F6F6F6"

[data]
stations=["Podgorica"]
timezone="Europe/Podgorica"
osm_shapes="zpcg-routes.osm.bz2"

[output]
filename="me_zpcg.gtfs.zip"
